CREATE ROLE dlg_admin WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:+LcyT6cszxpR2otTM/34Ug==$4D9LEfbFOt1YSZ+KOccjFTinwnJc+/ehF+zRI4QTPZU=:sJrIYXD3/YrwzCChHbdDryFxueKZESfhH1XDufsM5sc=';
